### ISSUE TITLE
Incorrect adjacency matrix implementation

### ISSUE THREAD

**Issue by mdrafiqulrabin** [myannuzzi/COSC-4353-Group-B#8]
https://github.com/myannuzzi/COSC-4353-Group-B/blob/aceb7e2a6b96e7fb00c81ff6d0bb0c8e23e082c1/userInput.py#L22

**Comment by myannuzzi** [comment]
Hello mdrafiqulrabin,

Thank you for the ticket. This line was trying to make a list of lists, but it didn't work. But instead of using a list of lists we decided to use the numpy library and its array features. This line and file will be modified and removed later today. 

Thank you!
-Mike Y

**Comment by myannuzzi** [comment]
The code for this file has been changed and we are no longer using it. I will be closing this issue.
Thank you,
Mike Y
