### ISSUE TITLE
Why delimiter='None' instead of delimiter=',' for reading csv?

### ISSUE THREAD

**Issue by mdrafiqulrabin** [myannuzzi/COSC-4353-Group-B#9]
https://github.com/myannuzzi/COSC-4353-Group-B/blob/aceb7e2a6b96e7fb00c81ff6d0bb0c8e23e082c1/CSV_File_Input.py#L4

**Comment by myannuzzi** [comment]
Hello mdrafiqulrabin,

None is acceptable as the default delimiter. If the delimiter was something else, say ';', then that would need to be specified. I am closing this ticket.

Thank you!
-Mike Y

**Comment by mdrafiqulrabin** [comment]
Suppose,

test.csv
--------

```
col1,col2,col3
1,2,3
4,5,6
7,8,9
```

test.py
-------

```
import pandas as pd

csv_file = "test.csv"

print("[delimiter=',' ]:")
df1 = pd.read_csv(csv_file, delimiter=',')
print("Shape:", df1.shape)
print(df1)

print("\n[delimiter='None'] :")
df2 = pd.read_csv(csv_file, delimiter='None')
print("Shape:", df2.shape)
print(df2)
```



@myannuzzi, can you run this code, share your output?
